### PR TITLE
/auth/google-auth endpoint and tests added

### LINKED ISSUE #21: [GoogleAuth] Connect Google login to the project
- Use `google-auth-library` library for google auth(It is already installed)
- Use `OAuth2Client` from this library for creating a `client` by using `clientId`
- Verify the id token for getting a `ticket` using the created `client`
- Write test for google auth in auth.spec.js

https://www.youtube.com/watch?v=5yeEpC3TEtg

----

### Cover more code with tests for auth.js controller
- write more tests in `controller/auth.spec.js`
- refactor already existing tests if needed

### PR DESCRIPTION
**Pull request by tufned**
### !!! Important !!! 
1. you should update `.env` files with GMAIL_ props both on backend and frontend
2. you can login only with test user: 
    s2satlasvk@gmail.com (email that we are using for mongo atlas)

---

### how to check: 
pressing the login with google button -> dev tools in browser -> network tab -> google-auth
- 👍  if success - response should look like this:
``` 
{
    "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
} 
```

- and the payload should be:
```
{
  "token": {
      "clientId": "230808534264-44...u6m.apps.googleusercontent.com",
      "client_id": "230808534264-44...lu6m.apps.googleusercontent.com",
      "credential": "eyJhbGciOiJSUzI1NiIsImtpZCI6IjBlMzQ1Z...,
      "select_by": "btn"
  }
}
```
`credential` is the _tokenId_

---

- tests are in `auth.spec.js`

For these tests it is a must to have `.env.test.local`
There you should use different SERVER_PORT and different database:
```
    MONGODB_URL=connection-string-to-our-own-db
    SERVER_PORT=8081
```

### CODE REVIEW

**Review by SeredenkoDS — APPROVED** [review]
Tested it by following the instructions.
1. copied the provided secrets into the respective .env.local files,
2. used login -> sign in with gmail using our s2satlasvk gmail,
3. checked network tab, clicked on google-auth, and payload/response are as expected.

Approving.

**Review by olehpona — APPROVED** [review]
Works great!

**Review by grbvtsk — APPROVED** [review]
really nice!

**Review by SachkovaYuliia — APPROVED** [review]

**Review by vlad-khrychov — COMMENTED** [review]
If I understand correctly, in the tests we are working with our real DB and in some tests we are sending a request to the Google API? We need mock google service in all tests and don't forget to work with mock db or modify it in env for tests.

**Review by vlad-khrychov — APPROVED** [review]

**Pull request merged**
